server:
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    internal_proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}
security.user.password: password
spring.thymeleaf.cache: false

targets:
  scheme: http
  uaa: ${targets.scheme}://localhost:8080/uaa
  menu: ${targets.scheme}://localhost:8083
  order: ${targets.scheme}://localhost:8085
  
---

spring:
  profiles: cloud 

security.require_ssl: true

targets:
  scheme: https
  uaa: ${targets.scheme}://wtran-springone.login.run.pivotal.io
  menu: ${targets.scheme}://wtran-microsec-menu.cfapps.io
  order: ${targets.scheme}://wtran-microsec-order.cfapps.io
